language: php
php:
  - '7.1'
  - '7.2'
services:
  - mysql
install: composer install
before_script:
  - cp .env.travis .env
  - php artisan key:generate
  - mysql -e "CREATE DATABASE missioncontrol_test;"
