language: php
php:
  - '7.1'
  - '7.2'
services:
  - mysql
install: composer install --no-dev
before_script:
  - cp .env.travis .env
  - php artisan key:generate
  - mysql -e "CREATE DATABASE missioncontrol_test;"
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script: phpunit --coverage-clover ./clover.xml
jobs:
  include:
    - stage: report
      php: '7.1'
      script: phpunit --coverage-clover ./clover.xml && ./cc-test-reporter after-build
